/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-19 09:06:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduce_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cute+Font&family=Diphylleia&family=Dokdo&family=Nanum+Brush+Script&family=Nanum+Gothic+Coding&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("@font-face {\n");
      out.write("    font-family: 'EF_jejudoldam';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2210-EF@1.0/EF_jejudoldam.woff2') format('woff2');\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@font-face {\n");
      out.write("    font-family: 'establishRoomNo703OTF';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2112@1.0/establishRoomNo703OTF.woff') format('woff');\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".div1{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".span1{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 150px;\n");
      out.write("	width: 500px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".span2{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 750px;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 40px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	background: linear-gradient(to top, #B3E5FC 40%, transparent 60%);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".div2{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 800px;\n");
      out.write("	width: 1000px;\n");
      out.write("	background-color: #F5F5F5;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".span3{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 900px;\n");
      out.write("	width: 350px;\n");
      out.write("	height: 40px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	background: linear-gradient(to top, #B3E5FC 40%, transparent 60%);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".div3{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 950px;\n");
      out.write("	width: 1000px;\n");
      out.write("	background-color: #F5F5F5;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".span4{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 1170px;\n");
      out.write("	width: 560px;\n");
      out.write("	height: 40px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	background: linear-gradient(to top, #B3E5FC 40%, transparent 60%);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".div4{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 350px;\n");
      out.write("	top: 1230px;\n");
      out.write("	width: 600px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#jejuair, #sklental, #socar, #yanolja, #yugiuhtte {\n");
      out.write("	width: 60px;\n");
      out.write("	height: 30px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(function(){\n");
      out.write("		$(\".div2\").hide();\n");
      out.write("		$(\".div3\").hide();\n");
      out.write("		$(\".div4\").hide();\n");
      out.write("		\n");
      out.write("		$(\".span2\").click(function(){\n");
      out.write("			$(\".div2\").toggle(\"slow\");\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\".span3\").click(function(){\n");
      out.write("			$(\".div3\").toggle(\"slow\");\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\".span4\").click(function(){\n");
      out.write("			$(\".div4\").toggle(\"slow\");\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#jejuair\").click(function(){\n");
      out.write("			window.open(\"https://www.jejuair.net\")\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#sklental\").click(function(){\n");
      out.write("			window.open(\"https://www.skcarrental.com\")\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#socar\").click(function(){\n");
      out.write("			window.open(\"https://www.socar.kr\")\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#yanolja\").click(function(){\n");
      out.write("			window.open(\"https://www.yanolja.com\")\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(\"#yugiuhtte\").click(function(){\n");
      out.write("			window.open(\"https://www.goodchoice.kr\")\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<span class=\"span1\"><h2 style=\"	font-family: 'EF_jejudoldam';\">제주도를 소개합니다:)</h2></span>\n");
      out.write("	\n");
      out.write("<div class=\"div1\">\n");
      out.write("	<img src=\"jeju/introduce.png\" style=\"width: 1000px; height: 500px;\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("	<span class=\"span2\"><h2 style=\"	font-family: 'EF_jejudoldam';\">제주도는요,</h2></span>\n");
      out.write("	\n");
      out.write("<div class=\"div2\">\n");
      out.write("	<h4 style=\"	font-family: 'establishRoomNo703OTF';\">제주도는 3면이 바다로 둘러 쌓여 어느 곳에서든 바다의 아름다움과 자연이 만든 경치를 즐길 수 있는 곳입니다.<pre></pre>\n");
      out.write("	산과 바다, 자연이 어우러진 아름다운 섬나라, 제주도에서의 행복한 시간을 <b>제주하다</b>와 함께 하세요♡\n");
      out.write("	</h4>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("	<span class=\"span3\"><h2 style=\"	font-family: 'EF_jejudoldam';\">제주도의 자랑거리는요,</h2></span>\n");
      out.write("	\n");
      out.write("<div class=\"div3\">\n");
      out.write("	<h4 style=\"	font-family: 'establishRoomNo703OTF';\"><b style=\"color: #A1887F;\">관광지</b><pre></pre>\n");
      out.write("	제주도에는 15개가 넘는 해수욕장과 한라산, 성산일출봉, 우도 등이 있어 다양한 테마의 여행을 즐길 수 있습니다.<pre></pre>\n");
      out.write("	<b style=\"color: #A1887F;\">음식</b><pre></pre>\n");
      out.write("	제주 은갈치, 연돈, 제주 흑돼지 등 여행객들의 배를 채워줄 맛집들이 많습니다. 배꼽시계가 울리지 않는, 제주에서의 식도락 여행을 즐겨보세요.\n");
      out.write("	</h4>\n");
      out.write("</div>\n");
      out.write("	\n");
      out.write("	<span class=\"span4\"><h2 style=\"	font-family: 'EF_jejudoldam';\">제주도 교통편 및 숙박 예약 바로가기</h2></span>\n");
      out.write("	\n");
      out.write("<div class=\"div4\">\n");
      out.write("	<img src=\"jeju/jejuair.png\" id=\"jejuair\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("	<img src=\"jeju/sklental.png\" id=\"sklental\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("	<img src=\"jeju/socar.png\" id=\"socar\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("	<img src=\"jeju/yanolja.png\" id=\"yanolja\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("	<img src=\"jeju/yugiuhtte.png\" id=\"yugiuhtte\">\n");
      out.write("</div>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
