/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-19 02:21:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cute+Font&family=Diphylleia&family=Dokdo&family=Nanum+Brush+Script&family=Nanum+Gothic+Coding&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);\n");
      out.write("\n");
      out.write("span * {\n");
      out.write("    font-family: 'OAGothic-ExtraBold';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/OAGothic-ExtraBold.woff2') format('woff2');\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slider{\n");
      out.write("    width: 640px;\n");
      out.write("    height: 480px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    top: 700px;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]{\n");
      out.write("    display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.imgs{\n");
      out.write("    padding: 0;\n");
      out.write("    margin: 0;\n");
      out.write("}\n");
      out.write("ul.imgs li{\n");
      out.write("/* 슬라이드가 겹쳐서 모여야 하므로 absolute 속성으로 배치 */\n");
      out.write("    opacity: 0; /* 체크한 라디오박스 순서의 슬라이드만 표시되도록 기본 투명도 설정 */\n");
      out.write("    list-style: none;\n");
      out.write("    padding: 0;\n");
      out.write("    margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bullets{\n");
      out.write("    position: absolute;\n");
      out.write("    left: 350px; /* 가로로 가운데 정렬 */\n");
      out.write("    top: -100px;\n");
      out.write("    transform: translateX(-50%);\n");
      out.write("    z-index: 997; /* 슬라이드 위에 보이도록 레이어 순위를 높임 */\n");
      out.write("}\n");
      out.write(".bullets label{\n");
      out.write("    display: inline-block; /* 한 줄로 불릿 나열*/\n");
      out.write("    border-radius: 50%; /* 원형 불릿으로 처리 */\n");
      out.write("    background-color: rgba(0,0,0,0.55);\n");
      out.write("    width: 20px; /* 불릿 너비 */\n");
      out.write("    height: 20px; /* 불릿 높이 */\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slider input[type=radio]:nth-child(1):checked~.bullets>label:nth-child(1){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(2):checked~.bullets>label:nth-child(2){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(3):checked~.bullets>label:nth-child(3){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(4):checked~.bullets>label:nth-child(4){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(5):checked~.bullets>label:nth-child(5){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(6):checked~.bullets>label:nth-child(6){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(7):checked~.bullets>label:nth-child(7){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(8):checked~.bullets>label:nth-child(8){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(9):checked~.bullets>label:nth-child(9){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(10):checked~.bullets>label:nth-child(10){\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".slider input[type=radio]:nth-child(1):checked~ul.imgs>li:nth-child(1){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(2):checked~ul.imgs>li:nth-child(2){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(3):checked~ul.imgs>li:nth-child(3){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(4):checked~ul.imgs>li:nth-child(4){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(5):checked~ul.imgs>li:nth-child(5){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(6):checked~ul.imgs>li:nth-child(6){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(7):checked~ul.imgs>li:nth-child(7){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(8):checked~ul.imgs>li:nth-child(8){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(9):checked~ul.imgs>li:nth-child(9){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write(".slider input[type=radio]:nth-child(10):checked~ul.imgs>li:nth-child(10){\n");
      out.write("    opacity: 1;\n");
      out.write("    z-index: 998;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.imgs li{\n");
      out.write("    position: absolute;\n");
      out.write("    opacity: 0;\n");
      out.write("    list-style: none;\n");
      out.write("    padding: 0;\n");
      out.write("    margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@font-face {\n");
      out.write("    font-family: 'Cafe24Supermagic-Bold-v1.0';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2307-2@1.0/Cafe24Supermagic-Bold-v1.0.woff2') format('woff2');\n");
      out.write("    font-weight: 700;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img.infinite_rotating_logo{\n");
      out.write("    animation: rotate_image 20s linear infinite;\n");
      out.write("    transform-origin: 50% 50%;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("@keyframes rotate_image{\n");
      out.write("	100% {\n");
      out.write("    	transform: rotate(360deg);\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dv17 img:hover {\n");
      out.write("  transform: translateY(-15px);\n");
      out.write("  transition: all 0.5s ease-in-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("	$(function(){\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		$(\"#slide1\").click(function(){\n");
      out.write("			$(\".dv2\").css(\"background-color\",\"#90CAF9\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide2\").click(function(){\n");
      out.write("			$(\".dv3\").css(\"background-color\",\"#B2DFDB\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide3\").click(function(){\n");
      out.write("			$(\".dv4\").css(\"background-color\",\"#FFECB3\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide4\").click(function(){\n");
      out.write("			$(\".dv5\").css(\"background-color\",\"#80DEEA\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide5\").click(function(){\n");
      out.write("			$(\".dv6\").css(\"background-color\",\"#FFF59D\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide6\").click(function(){\n");
      out.write("			$(\".dv7\").css(\"background-color\",\"#E0E0E0\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide7\").click(function(){\n");
      out.write("			$(\".dv8\").css(\"background-color\",\"#80CBC4\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide8\").click(function(){\n");
      out.write("			$(\".dv9\").css(\"background-color\",\"#D7CCC8\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide9\").click(function(){\n");
      out.write("			$(\".dv10\").css(\"background-color\",\"#B3E5FC\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv11\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#slide10\").click(function(){\n");
      out.write("			$(\".dv11\").css(\"background-color\",\"#A5D6A7\").css(\"z-index\",\"2\")\n");
      out.write("			$(\".dv2\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv3\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv4\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv5\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv6\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv7\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv8\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv9\").css(\"z-index\",\"0\")\n");
      out.write("			$(\".dv10\").css(\"z-index\",\"0\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		var slideIndex = 1;\n");
      out.write("		var slideInterval = setInterval(function() {\n");
      out.write("  			$(\"#slide\" + slideIndex).trigger('click');\n");
      out.write("  			slideIndex++;\n");
      out.write("  			if (slideIndex > 10) {\n");
      out.write("    			slideIndex = 1;\n");
      out.write("  				}\n");
      out.write("			}, 3000);\n");
      out.write("		\n");
      out.write("		$(\"#im1\").mouseover(function(){\n");
      out.write("			$(\"#im1\").css(\"width\",\"49%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im2\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im3\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im4\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#im2\").mouseover(function(){\n");
      out.write("			$(\"#im2\").css(\"width\",\"49%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im1\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im3\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im4\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#im3\").mouseover(function(){\n");
      out.write("			$(\"#im3\").css(\"width\",\"49%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im1\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im2\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im4\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		$(\"#im4\").mouseover(function(){\n");
      out.write("			$(\"#im4\").css(\"width\",\"49%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im1\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im2\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("			$(\"#im3\").css(\"width\",\"16.3%\").css(\"transition\",\"0.5s ease-in-out\")\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"dv2\" style=\"position: absolute; z-index: 1; background-color: #90CAF9; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 180px; height: 30px; font-weight: 300;\">제주 숨은 물놀이 맛집</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">여름 더위는 여기서\n");
      out.write("	<pre>[함덕 해수욕장]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv3\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주의 랜드마크</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">자연이 만든 신비\n");
      out.write("	<pre>[한라산]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv4\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주 속 해수욕장</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">한국의 하와이\n");
      out.write("	<pre>[금농 해수욕장]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv5\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주 속 숨은 섬</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">섬 안에 또 다른 섬\n");
      out.write("	<pre>[우도]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv6\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주 포토 스팟</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">봄 냄새 물씬, 노란 빛\n");
      out.write("	<pre>[유채꽃 축제]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv7\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주를 아는 방법</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">제주의 모든 것!\n");
      out.write("	<pre>[국립 제주 박물관]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv8\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주 산책 맛집</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">걷다 보면 만나는 아름다움\n");
      out.write("	<pre>[한담마을]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv9\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주의 공기</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">숲의 맑은 공기로 ReFresh!\n");
      out.write("	<pre>[사려니숲]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv10\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주 바다 맛집</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">바다빛 향연\n");
      out.write("	<pre>[협재 해수욕장]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv11\" style=\"position: absolute; z-index: 0; height: 560px; top: 78px; width: 1690px;\">\n");
      out.write("	<span style= \"position: absolute; border-radius:20px 20px 20px 0px; padding-left:8px; background-color: black; color: white; padding-top: 3px; margin-left: 390px; margin-top: 170px; width: 140px; height: 30px; font-weight: 300;\">제주 산책 맛집</span>\n");
      out.write("	<span style= \"position: absolute; padding-left:8px; color: #424242; padding-top: 5px; margin-left: 380px; margin-top: 230px; font-weight: 800;font-size: 35px;\">올레길 걸으러 올래?\n");
      out.write("	<pre>[올레길]<pre><a href=\"\" style=\"font-weight: 300; font-size: 14px; text-decoration: underline; color: #757575\">자세히 보기</a>\n");
      out.write("	</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div  class=\"slider\" style=\"position: relative;\">\n");
      out.write(" 	<input type=\"radio\" name=\"slide\" id=\"slide1\" checked>\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide2\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide3\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide4\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide5\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide6\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide7\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide8\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide9\">\n");
      out.write("    <input type=\"radio\" name=\"slide\" id=\"slide10\">\n");
      out.write("    <ul id=\"imgholder\" class=\"imgs\">\n");
      out.write("        <li><img src=\"jeju/hamduk.png\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/halla.jpg\" style=\"position: absolute;  border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/geumnong.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/woodo.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/yuchae.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/museum.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/handam.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/forest.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/hyupjae.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("        <li><img src=\"jeju/olleh.jpg\" style=\"position: absolute; border-radius: 10px 10px; width: 820px; height: 550px; right: -1398px; top: -550px;\"></li>\n");
      out.write("    </ul>\n");
      out.write("    <div class=\"bullets\">\n");
      out.write("        <label for=\"slide1\">&nbsp;</label>\n");
      out.write("        <label for=\"slide2\">&nbsp;</label>\n");
      out.write("        <label for=\"slide3\">&nbsp;</label>\n");
      out.write("        <label for=\"slide4\">&nbsp;</label>\n");
      out.write("        <label for=\"slide5\">&nbsp;</label>\n");
      out.write("        <label for=\"slide6\">&nbsp;</label>\n");
      out.write("        <label for=\"slide7\">&nbsp;</label>\n");
      out.write("        <label for=\"slide8\">&nbsp;</label>\n");
      out.write("        <label for=\"slide9\">&nbsp;</label>\n");
      out.write("        <label for=\"slide10\">&nbsp;</label>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv12\" style=\"width: 845px; height: 20px; margin-top: 300px; margin-left: 380px;\">\n");
      out.write("	<img src=\"jeju/whale.png\" style=\"width: 40px; height: 40px;\">\n");
      out.write("	<span style=\"color: #1976D2; font-weight: 800; vertical-align: middle;\">제주하다 PICK! ||</span>\n");
      out.write("	<span style=\"font-size:35px; font-weight: 800; color: #2962FF; vertical-align: middle;\"><b style=\"font-family: 'Cafe24Supermagic-Bold-v1.0'\">제주도 대표 관광지</b></span>\n");
      out.write("	<pre></pre>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv13\" style=\"position: absolute; width: 1000px; height: 400px; margin-top: 40px; margin-left: 350px;\">\n");
      out.write("	<ul>\n");
      out.write("			<img src=\"jeju/aquaplanet.jpg\" style=\"width: 24.5%; height: 300px; cursor: pointer;\" id=\"im1\">\n");
      out.write("			<img src=\"jeju/manjang.jpg\" style=\"width: 24.5%; height: 300px; cursor: pointer;\" id=\"im2\">\n");
      out.write("			<img src=\"jeju/sungsan.jpg\" style=\"width: 24.5%; height: 300px; cursor: pointer;\" id=\"im3\">\n");
      out.write("			<img src=\"jeju/racing.png\" style=\"width: 24.5%; height: 300px; cursor: pointer;\" id=\"im4\">\n");
      out.write("	</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv14\" style=\"width: 845px; height: 20px; margin-top: 360px; margin-left: 380px;\">\n");
      out.write("	<img src=\"jeju/whale.png\" style=\"width: 40px; height: 40px;\">\n");
      out.write("	<span style=\"color: #1976D2; font-weight: 800; vertical-align: middle;\">제주하다 추천! ||</span>\n");
      out.write("	<span style=\"font-size:35px; font-weight: 800; color: #2962FF; vertical-align: middle;\"><b style=\"font-family: 'Cafe24Supermagic-Bold-v1.0'\">제주도 여행 코스</b></span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv15\" style=\"position: absolute; width: 1000px; height: 400px; margin-top: 40px; margin-left: 350px;\">\n");
      out.write("	<ul>\n");
      out.write("			<img src=\"jeju/aquaplanet.jpg\" style=\"width: 24.5%; height: 300px;\" id=\"im1\">\n");
      out.write("			<img src=\"jeju/manjang.jpg\" style=\"width: 24.5%; height: 300px;\" id=\"im2\">\n");
      out.write("			<img src=\"jeju/sungsan.jpg\" style=\"width: 24.5%; height: 300px;\" id=\"im3\">\n");
      out.write("			<img src=\"jeju/racing.png\" style=\"width: 24.5%; height: 300px;\" id=\"im4\">\n");
      out.write("	</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv16\" style=\"width: 845px; height: 20px; margin-top: 360px; margin-left: 380px;\">\n");
      out.write("	<img src=\"jeju/whale.png\" style=\"width: 40px; height: 40px;\">\n");
      out.write("	<span style=\"color: #1976D2; font-weight: 800; vertical-align: middle;\">제주하다와 더욱 즐기자! ||</span>\n");
      out.write("	<span style=\"font-size:35px; font-weight: 800; color: #2962FF; vertical-align: middle;\"><b style=\"font-family: 'Cafe24Supermagic-Bold-v1.0'\">이벤트 모음</b></span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"dv17\" style=\"position: absolute; width: 1000px; height: 400px; margin-top: 40px; margin-left: 350px;\">\n");
      out.write("	<ul>\n");
      out.write("			<img src=\"jeju/event1.png\" style=\"width: 32.9%; height: 300px; cursor: pointer;\">\n");
      out.write("			<img src=\"jeju/event2.png\" style=\"width: 32.9%; height: 300px; cursor: pointer;\">\n");
      out.write("			<img src=\"jeju/event3.png\" style=\"width: 32.9%; height: 300px; cursor: pointer;\">\n");
      out.write("	</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"logo-area\" style=\"z-index: 998; position: absolute; top: 100px; left: 800px;\">\n");
      out.write("	<img src=\"jeju/spin.png\" class=\"infinite_rotating_logo\" style=\"width: 130px; height: 130px;\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
